# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-25 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistToBoardgame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('min_best_players', models.IntegerField()),
                ('max_best_players', models.IntegerField()),
                ('min_age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('min_play_time', models.IntegerField()),
                ('max_play_time', models.IntegerField()),
                ('bg_image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('bgg_code', models.IntegerField()),
                ('stddev', models.FloatField()),
                ('users_rated', models.IntegerField()),
                ('fans', models.IntegerField()),
                ('num_owned', models.IntegerField()),
                ('num_plays', models.IntegerField()),
                ('num_wish', models.IntegerField()),
                ('sub_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BoardgameExpansion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_bg', to='website.Boardgame')),
                ('boardgame_expansion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bg_expansion', to='website.Boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryToBoardgame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DesignerToBoardgame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Boardgame')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Designer')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyToBoardgame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MechanicToBoardgame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_value', models.IntegerField()),
                ('rank_name', models.CharField(max_length=255)),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TypeToBoardgame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Boardgame')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Type')),
            ],
        ),
        migrations.AddField(
            model_name='mechanictoboardgame',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Type'),
        ),
        migrations.AddField(
            model_name='familytoboardgame',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Type'),
        ),
        migrations.AddField(
            model_name='categorytoboardgame',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Type'),
        ),
        migrations.AddField(
            model_name='artisttoboardgame',
            name='boardgame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Boardgame'),
        ),
    ]
