# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-25 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.RemoveField(
            model_name='familytoboardgame',
            name='boardgame',
        ),
        migrations.RemoveField(
            model_name='familytoboardgame',
            name='type',
        ),
        migrations.DeleteModel(
            name='FamilyToBoardgame',
        ),
    ]
