# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-25 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180825_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyToBoardgame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Boardgame')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Type')),
            ],
        ),
    ]
