# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-25 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180825_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='average',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='weight',
            field=models.FloatField(),
        ),
    ]
