# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-28 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180825_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='bgg_image_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='img_caption',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
