# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-29 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20180828_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(max_length=500)),
                ('bgg_file_page_id', models.IntegerField()),
                ('bgg_file_id', models.IntegerField()),
                ('file_desc', models.TextField()),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Boardgame')),
            ],
        ),
    ]
