# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-29 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
