# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-29 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20180829_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_title', models.CharField(max_length=500)),
                ('forum_category', models.CharField(max_length=500)),
                ('bgg_forum_id', models.IntegerField()),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Boardgame')),
            ],
        ),
    ]
